load('../Tiltfile', 'remote_development')

# NB: attach() is intended for attaching to existing
# deployments. Normally, you'd do the kubectl apply
# outside of the main
docker_build(
  'remote-dev-test-image'
)
local('kubectl apply -f deployment.yaml')

remote_development(
  obj='deployment/example-nodejs',
  container_selector='my-container',
  dockerfile='Dockerfile.dev',
  disable_probes=True,
  live_update=[
    sync('./app', '/app'),
  ],
  port_forwards=[
    8080:8080,
    9229:9229
  ]
)